baseurl = "http://thefunctionalists.com/blog/"
languageCode = "en-us"
title = "The Functionalists - Blog"
theme = "steam"
paginate = 10

[params]

	title = "The Functionalists - Blog"
	Subtitle = "We write software that simply works"
	# You can choose between green, orange, red and blue.
	themeColor = "yellow"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "The Functionalists"
	description = "We write software that simply works"
	twitter = "theflists" # optional
	github = "thefunctionalists" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	# comments = "disqus"


	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
